version: '3.3'

services:
 frontend:
  build:
   context: ./next-app
  restart: always
  ports:
   - '3000:3000'
  labels:
   - traefik.http.routers.next-app.rule=Host(`www.yandre.me`)
   - traefik.http.services.next-app.loadbalancer.server.port=3000
  networks:
   - reverse

networks:
 reverse:
  external: true
