version: '3.3'

services:
 proxy:
  image: traefik
  command: --providers.docker
  restart: always
  ports:
   - '80:80'
   - '433:433'
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  networks:
   - reverse

 db:
  image: mariadb:10.6.1-focal
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  env_file: .env
  environment:
   MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MARIADB_DATABASE: ${MYSQL_DATABASE}
   MARIADB_USER: ${MYSQL_USER}
   MARIADB_PASSWORD: ${MYSQL_PASSWORD}
  networks:
   - reverse

 backend:
  depends_on:
   - db
  image: wordpress:latest
  volumes:
   - wordpress:/var/www/html
   - ./wp-content:/var/www/html/wp-content
  restart: always
  expose:
   - '80'
  env_file: .env
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: ${MYSQL_USER}
   WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
   WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  labels:
   - traefik.http.routers.backend.rule=Host(`frozen.yandre.me`)
   - traefik.http.services.backend.loadbalancer.server.port=80
  networks:
    - reverse

networks:
 reverse:
  external: true
volumes:
 db_data:
 wordpress: